WITH REGISTRATION AS(
 SELECT 
       INITCAP(REG_NAME) AS REG_NAME, 
       SR_ID 
FROM 
       AB_SETUP_REGISTRATION  
WHERE 
       REG_TYPE = 'COMPANY'
  AND (ORG_ID = :GV_ORG_ID OR :GV_ORG_ID IN ( 1004,1006,1007,1005))
ORDER BY
       SR_ID ASC
),
PRODUCT_NAME AS (
    SELECT 
        ITM.ITEM_NAME || ' ' || ITM.PACKING_SIZE || '('|| ITM.UNIT ||') '|| PACKING AS ITEM_NAME,
        ITEM_ID 
    FROM AB_ITEMS_MASTER ITM
    WHERE ITM.STATUS='Y'
    ORDER BY ITM.ITEM_ID ASC
),
PRODCUT_NAME_MULTIPLE AS (
    SELECT  
        ASOD.SOD_ID,
        LISTAGG(DISTINCT ITM.ITEM_ID, ', ') WITHIN GROUP (ORDER BY ITM.ITEM_ID) AS ITEM_ID,
        LISTAGG(DISTINCT ITM.ITEM_NAME, ', ') WITHIN GROUP (ORDER BY ITM.ITEM_NAME) AS PRODUCT_NAME
    FROM AB_SO_ORDER_DET ASOD
    JOIN AB_SO_ORDER_DET ASODS ON ASODS.SOD_IDS = ASOD.SOD_ID
    JOIN PRODUCT_NAME ITM ON ITM.ITEM_ID = ASODS.ITEM_ID
    WHERE ASOD.ORG_ID = :GV_ORG_ID AND ASOD.SOD_TYPE = '840'
    GROUP BY ASOD.SOD_ID
),
CATEGORY_NAME AS (
    SELECT  
        ALD.LOOKUP_DET_NAME AS PRODUCT_CATEGORY,
        ALD.DET_ID AS CATEGORY_ID
    FROM AB_LOOKUP_DETAIL ALD   
    WHERE ALD.LOOKUP_ID = 001 AND ALD.STATUS = 'Y'
),
LOOKUP AS(
    SELECT DET_ID, LOOKUP_DET_NAME
    FROM AB_LOOKUP_DETAIL
    WHERE STATUS='Y'
),
CHART_OF_ACCOUNT AS(
    SELECT COA_ID, SUB_ACCOUNT_TYPE, ACCOUNT_TITLE
    FROM AB_FIN_COA
    WHERE STATUS='Y'
),
USER_APPROVAL AS (
       SELECT
        APP_IDS AS SALE_ID,
        INITCAP(CREATED_BY) ||' ('|| TO_CHAR(CREATED_ON,'DD-MON-YYYY') ||')' APPROAL_BY,
        CREATED_ON,
        APPROVAL_STATUS
    FROM AB_USER_ACTION_APPROVAL
    WHERE APP_TYPE = '820' AND STATUS = 'Y' 
    AND APPROVAL_STATUS='APPROVED' AND ORG_ID=:GV_ORG_ID
),
CORPORATE_BAGS AS (
    SELECT 
        SO_ID,
        SUM(NO_BAGS) AS TOTAL_CORPORATE_BAGS
    FROM AB_SO_ORDER_DET
    WHERE STATUS = 'Y'
    GROUP BY SO_ID
),
NOARMAL_SALE_ORDER AS (
 SELECT          
        SO.SO_IDS,
        SUM(SOD.NO_BAGS) AS TOTAL_BAGS       
   FROM 
                     AB_SO_ORDER_HEAD SO 
             JOIN AB_SO_ORDER_DET SOD ON SOD.SO_ID = SO.SO_ID AND SOD.STATUS = 'Y'
             JOIN AB_SO_ORDER_HEAD ASO ON ASO.SO_ID = SO.SO_IDS
             JOIN AB_SO_ORDER_DET ASOD ON ASOD.SO_ID = ASO.SO_ID
             JOIN AB_SO_ORDER_DET ASODS ON ASODS.SOD_IDS = ASOD.SOD_ID
            JOIN AB_SO_ORDER_DET ADOS ON ADOS.SOD_IDS = SOD.SOD_ID
            JOIN AB_SO_ORDER_HEAD ADOSM ON ADOSM.SO_ID = ADOS.SO_ID
             JOIN USER_APPROVAL APP ON  APP.SALE_ID=ADOS.SOD_ID
     WHERE
                SO.ORG_ID=:GV_ORG_ID
                AND ASODS.ITEM_ID =  SOD.ITEM_ID
                AND SO.STATUS='Y'
                AND  ADOSM.SO_TYPE ='SALE SHIPMENT'

                GROUP BY SO.SO_IDS
),
ADVANCE_SALE_ORDER AS (
 SELECT          
        SO.SO_IDS,
        SUM(SOD.NO_BAGS) AS TOTAL_BAGS       
    FROM 
                     AB_SO_ORDER_HEAD SO 
             JOIN AB_SO_ORDER_DET SOD ON SOD.SO_ID = SO.SO_ID AND SOD.STATUS = 'Y'
             JOIN AB_SO_ORDER_HEAD ASO ON ASO.SO_ID = SO.SO_IDS
             JOIN AB_SO_ORDER_DET ASOD ON ASOD.SO_ID = ASO.SO_ID
             JOIN AB_SO_ORDER_DET ASODS ON ASODS.SOD_IDS = ASOD.SOD_ID
            JOIN AB_SO_ORDER_DET ADOS ON ADOS.SOD_IDS = SOD.SOD_ID
            JOIN AB_SO_ORDER_DET ADOSU ON ADOSU.SOD_IDS = ADOS.SOD_ID
          JOIN AB_SO_ORDER_HEAD ADOSM ON ADOSM.SO_ID = ADOSU.SO_ID
           JOIN USER_APPROVAL APP ON  APP.SALE_ID=ADOSU.SOD_ID
     WHERE
                SO.ORG_ID=:GV_ORG_ID
                AND ASODS.ITEM_ID =  SOD.ITEM_ID
                AND SO.STATUS='Y'
                AND ADOSM.SO_TYPE = 'SALE SHIPMENT'
                 GROUP BY SO.SO_IDS
)
SELECT
    SO.SO_ID,
    SO.COA_ID,
    TO_CHAR(SO.ORDER_DATE ,'DD-MON-YYYY') ORDER_DATE,
    SO.PARTY_ORDER_NO,
    SO.PAYMENT_ID,
    SO.COMPANY_ID,
    CB.TOTAL_CORPORATE_BAGS AS CORPORATE_BAGS,
    NVL(NSO.TOTAL_BAGS,0) AS NSO_BAGS,
    NVL(ASO.TOTAL_BAGS,0) AS ASO_NO_BAGS,
    CB.TOTAL_CORPORATE_BAGS - NVL(NSO.TOTAL_BAGS,0) - NVL(ASO.TOTAL_BAGS,0) AS REMAINING_BAGS,
    ACCOUNT_TITLE AS PARTY_NAME,
    ASR.REG_NAME AS COMPANY_NAME,
    INITCAP(L.LOOKUP_DET_NAME) AS PAYMENT_TERM,
    SO.CREATED_BY ||'( '|| TO_CHAR(SO.CREATED_ON,'DD-MON-YYYY HH:MI:SS AM')||')' AS ADD_BY,
    'Detail Corporate' as Detail_Corporate
FROM AB_SO_ORDER_HEAD SO 
JOIN CORPORATE_BAGS CB ON CB.SO_ID = SO.SO_ID
LEFT JOIN CHART_OF_ACCOUNT COA ON COA.COA_ID = SO.COA_ID
LEFT JOIN REGISTRATION ASR ON ASR.SR_ID = SO.COMPANY_ID 
LEFT JOIN LOOKUP L ON L.DET_ID = SO.PAYMENT_ID 
LEFT JOIN NOARMAL_SALE_ORDER NSO ON NSO.SO_IDS = SO.SO_ID
LEFT JOIN ADVANCE_SALE_ORDER ASO ON ASO.SO_IDS = SO.SO_ID
WHERE
    TRUNC(SO.ORDER_DATE) BETWEEN NVL(TO_DATE(:P959_FROM_DATE, 'DD-MON-YYYY'), TRUNC(SO.ORDER_DATE)) 
    AND NVL(TO_DATE(:P959_TO_DATE, 'DD-MON-YYYY'), TRUNC(SO.ORDER_DATE))
    AND SO.STATUS = 'Y'
    AND SO.SO_TYPE = '840'
    AND SO.ORG_ID = :GV_ORG_ID
    AND (:P959_PRODUCT_CATEGORY IS NULL OR EXISTS (
        SELECT 1 FROM AB_SO_ORDER_DET SOD2
        WHERE SOD2.SO_ID = SO.SO_ID
        AND SOD2.PRODUCT_CATEGORY_ID IN (
            SELECT REGEXP_SUBSTR(:P959_PRODUCT_CATEGORY, '[^:]+', 1, LEVEL) 
            FROM DUAL 
            CONNECT BY REGEXP_SUBSTR(:P959_PRODUCT_CATEGORY, '[^:]+', 1, LEVEL) IS NOT NULL
        )
    ))
    AND (:P959_PRODUCT_NAME IS NULL OR EXISTS (
        SELECT 1 FROM AB_SO_ORDER_DET SOD2
        WHERE SOD2.SO_ID = SO.SO_ID
        AND SOD2.ITEM_ID IN (
            SELECT REGEXP_SUBSTR(:P959_PRODUCT_NAME, '[^:]+', 1, LEVEL) 
            FROM DUAL 
            CONNECT BY REGEXP_SUBSTR(:P959_PRODUCT_NAME, '[^:]+', 1, LEVEL) IS NOT NULL
        )
    ))
ORDER BY SO.ORDER_DATE DESC;
